### ISSUE TITLE
В чем назначение анализаторов index_ru и search_ru

### ISSUE THREAD

**Issue by ivan-ilinov** [asyncee/elasticsearch-russian-config#1]
Добрый день!
Поясните, пожалуйста, в каких случаях следует использовать анализатор index_ru, а в каких - search_ru?

**Comment by asyncee** [comment]
Здравствуйте!

Если внимательно посмотреть, то можно будет увидеть различие анализаторов, конкретно - в токенизаторе.

Анализатор index_ru имеет токенизатор типа nGram от 4 до 20 символов, а это значит что индексируемое слово будет разбиваться на такие токены:

слово: французский

фран
франц
француз
...

ранц
анцу

...

и так далее.

Анализатор search_ru используется для поиска - он имеет стандартный токенизатор.

Таким образом, если у нас есть проиндексированный документ, в котором содержится фраза  "французская мода", например, то при поиске слову "француз" этот документ будет содержаться в поисковой выдаче.

Подробнее о токенизаторах вы можете уточнить в официальной документации.

**Comment by ivan-ilinov** [comment]
Да, спасибо, я заметил, что различие в фильтре nGram.

Мой вопрос касался именно практического смысла использования того или иного анализатора.

Вероятно, index_ru удобен для автокомплита, который пытается предугадать поисковый запрос, а search_ru - для формирования итоговой выдачи запроса. Так?

**Comment by asyncee** [comment]
В данном случае конкретно я (не знаю как остальные) использую index_ru в момент индексации данных, когда документы обрабатываются и попадают в индекс, а search_ru - именно для поиска по этому индексу. Данное решение неплохо себя показало для формирования именно итоговой выдачи, хотя для автокомплита её, конечно, тоже можно использовать, но, с фильтром nGram я не могу предсказать, насколько корректными будут результаты подсказок.
