### ISSUE TITLE
Токенизатор nGram иногда ломает подсветку

### ISSUE THREAD

**Issue by impworks** [asyncee/elasticsearch-russian-config#2]
Использовал данный конфиг для простейшего поиска по ФИО. Иногда результат выглядел неожиданно:

![image](https://user-images.githubusercontent.com/604496/35751547-0a315df6-086a-11e8-81b8-609fd7780a00.png)

Опытным путём определил, что проблема возникает из-за токенизатора `n_gram`, который используется в анализаторе для индексации. Замена его на `standard` исправляет ситуацию.

Вот ссылка на gist с конфигом (в виде .NET) и запросом\ответом:
https://gist.github.com/impworks/8fd8e15106129cb785e340ecf96c8041

Для чего именно был использован данный токенизатор? На что повлияет вместо него использовать `standard`?

**Comment by asyncee** [comment]
На самом деле под каждую задачу поиск можно настраивать отдельно, и нет одного общего решения, хорошо работающего для всех.

Если вам подходит стандартный токенизатор — используйте его.

Различие в токенизаторах в том, что первый разбивает текст на слова с ограниченной максимальной длиной, а второй на триграммы.

Соответственно массив данных, попадающий в индекс — разный, отсюда следуют разные веса для поисковых запросов и итоговая релевантность, это к вопросу о влиянии токенизатора.

Этот конфиг достаточно старый и был использован для работы на сайтах с большим количеством объявлений / продуктов, где n-gram токенизатор показал хорошие результаты.
