### ISSUE TITLE
Проект с elasticsearch

### ISSUE THREAD

**Issue by AndreyErmilov** [asyncee/elasticsearch-russian-config#3]
Станислав, здравствуйте!
Не нашел другого способа как с вами связаться. Прошу прощения за issue не по делу.

Скажите, пожалуйста, делаете ли вы проекты на заказ и если да, то напишите, пожалуйста, мне на почту andrey@funkypunky.ru ваши контакты.

Спасибо,
Андрей

**Comment by asyncee** [comment]
Здравствуйте, Андрей!

К сожалению, на данный момент я не занимаюсь проектами на заказ.

С уважением,
Станислав

**Comment by AndreyErmilov** [comment]
Станислав, понял, спасибо за ответ.

Если что-то изменится – напишите, пожалуйста. Проект не очень большой, но связан с не совсем тривиальной настройкой Elasticsearch и мне показалось, что вы в этом вопросе хорошо разбираетесь.

С уважением,
Андрей
